### PR TITLE
solved issue being unable to add marker

### LINKED ISSUE #1: Bug: can't add a new marker
After clicking the Save button on `AddMarkerModal`, app crashes with the error message as in the  attached screenshot.

Pull requests are welcome, the best contributor gets to choose the pizza style for the next workshop. Enjoy!

**Hint:** Marker form was implemented in a lazy way using [uncontrolled components](https://reactjs.org/docs/uncontrolled-components.html). We keep references to form input fields in the `AddMarkerModal` and then read values from them when submitting. Since we refactored the input fields, that binding no longer works. Best way to fix this would be to use [controlled components](https://reactjs.org/docs/forms.html), and write a method to update form fields in `AddMarkerModal` component and then pass it to child `InputField`s. 

screen shot 2017-10-06 at 10 14 37

### PR DESCRIPTION
**Pull request by gboduljak**
Edit by ikovic: fixes #1

### CODE REVIEW

**Comment by ikovic** [comment]
I see you have some trouble with formatting, I'll add some stuff to `master` which will make life easier for you.

**Comment by ikovic** [comment]
@gboduljak please merge master to your branch, I've added a precommit hook which will format the staged code. You can use [prettier](https://github.com/prettier/prettier#editor-integration) with your editor.

File: src/components/InputField/index.js [hunk 1]
```diff
@@ -1,18 +1,24 @@
...
+    <div className="formRow">
+      <label htmlFor={id}>{label}</label>
+      <input
+        style={{ marginLeft: '4px' }}
+        type="text"
+        name={name}
+        id={id}
+        className="formInput"
+        onChange={wrappedOnChange}
+        ref={input => (this.name = input)}
```
Comment (ikovic) [inline src/components/InputField/index.js]: We don't need this anymore since we are using `onChange` to get the field value, instead of DOM API which we use via `ref`.

**Comment by ikovic** [comment]
Great job, kudos for both being first and solving the problem! We'll wait until the next workshop to see if anyone else will take a different approach, I'll merge the best solution then. 

Also, you'll have your 5 minutes on the next workshop to explain how closures work in JS and how you used them to solve the issue :)

**Comment by gboduljak** [comment]
@ikovic may you have a look on this PR again? I think I commited all review proposed changes.

**Comment by ikovic** [comment]
@gboduljak PR is OK, I've pushed a change on your branch with some code formatting. We'll merge this today if nobody else gives a try :)

**Review by ikovic — APPROVED** [review]
